import { readFile, writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

// Generates supabase/migrations/0005_reseed_catalog.sql from the demo catalog
// in src/lib/catalog.ts, so the SQL and the storefront can never disagree
// about a price, a SKU or a stock level. Re-run this after editing the catalog.

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const source = await readFile(join(root, "src/lib/catalog.ts"), "utf8");

function sql(value) {
  return `'${String(value).replace(/'/g, "''")}'`;
}

// Parse the `catalog` array out of the TypeScript source. Deliberately narrow:
// it matches the shape this file itself writes, and throws loudly if the
// catalog is restructured rather than silently emitting a wrong catalog.
const start = source.indexOf("export const catalog: Product[] = [");
if (start === -1) throw new Error("could not find `export const catalog` in catalog.ts");

const body = source.slice(start);
const productRe =
  /\{\s*id:\s*"([^"]+)",\s*name:\s*"([^"]+)",\s*slug:\s*"([^"]+)",\s*category:\s*"([^"]+)",\s*priceCents:\s*(\d+),\s*imageUrl:\s*[^,]+,\s*description:\s*\n?\s*"([^"]*)",[\s\S]*?variants:\s*\[([\s\S]*?)\],\s*\},/g;

const products = [];
for (const match of body.matchAll(productRe)) {
  const [, , name, slug, category, priceCents, description, variantBlock] = match;

  const variantRe =
    /variant\("[^"]+",\s*(\d+),\s*"([^"]+)",\s*(\d+),\s*(\d+),\s*"([^"]+)"\)/g;
  const variants = [];
  for (const v of variantBlock.matchAll(variantRe)) {
    const [, , title, vPrice, stock] = v;
    variants.push({ title, priceCents: Number(vPrice), stock: Number(stock) });
  }

  if (variants.length === 0) throw new Error(`${slug} has no variants`);

  products.push({
    name,
    slug,
    category,
    priceCents: Number(priceCents),
    description: description ?? "",
    variants,
  });
}

if (products.length !== 8) {
  throw new Error(`expected 8 products, parsed ${products.length}`);
}

const statements = [];

products.forEach((product, index) => {
  statements.push(
    `insert into public.products (id, name, slug, description, status, category, sort_order)
values (
  gen_random_uuid(),
  ${sql(product.name)},
  ${sql(product.slug)},
  ${sql(product.description)},
  'active',
  ${sql(product.category)},
  ${index}
);`,
  );

  product.variants.forEach((variant, vIndex) => {
    const sku = `LS-${String(product.slug)
      .slice(0, 3)
      .toUpperCase()}-${String(index + 1).padStart(2, "0")}-${String(vIndex + 1).padStart(2, "0")}`;
    statements.push(
      `insert into public.product_variants (id, product_id, title, sku, price_cents, currency, stock, position, is_default, is_active)
select
  gen_random_uuid(), p.id,
  ${sql(variant.title)},
  ${sql(sku)},
  ${variant.priceCents},
  'usd',
  ${variant.stock},
  ${vIndex},
  ${vIndex === 0},
  true
from public.products p where p.slug = ${sql(product.slug)};`,
    );
  });
});

const sql_out = `-- Reseeds the catalog from src/lib/catalog.ts.
--
-- Generated by scripts/generate-reseed.mjs. Do not hand-edit: re-run the
-- generator after changing the storefront catalog.
--
-- Why this exists: the rows previously in products/product_variants were
-- placeholders. Every product had a single variant titled 'Default' with a
-- generated SKU, sort_order was 0 across the board, and price_cents was 100x
-- too large because 0001_schema.sql assumed products.price held dollars when
-- it already held cents.
--
-- Safe to re-run: child tables are truncated first, and the inserts are keyed
-- on slug so a second run reproduces the same catalog with new variant ids.
--
-- ids are generated by gen_random_uuid(). Nothing in the app depends on a
-- fixed product id — artwork and routing key off slug.

begin;

-- order_items references products and product_variants, so it must be emptied
-- before the catalog is replaced.
truncate table public.order_items, public.order_events, public.orders, public.email_log restart identity;

delete from public.product_variants;
delete from public.products;

${statements.join("\n\n")}

commit;

-- Make PostgREST pick up the new rows without a restart.
notify pgrst, 'reload schema';
`;

await writeFile(
  join(root, "supabase/migrations/0005_reseed_catalog.sql"),
  sql_out,
  "utf8",
);

console.log(
  `wrote 0005_reseed_catalog.sql — ${products.length} products, ${products.reduce((n, p) => n + p.variants.length, 0)} variants`,
);