-- Reseeds the catalog from src/lib/catalog.ts.
--
-- Generated by scripts/generate-reseed.mjs. Do not hand-edit: re-run the
-- generator after changing the storefront catalog.
--
-- Why this exists: the rows previously in products/product_variants were
-- placeholders. Every product had a single variant titled 'Default' with a
-- generated SKU, sort_order was 0 across the board, and price_cents was 100x
-- too large because 0001_schema.sql assumed products.price held dollars when
-- it already held cents.
--
-- Safe to re-run: child tables are truncated first, and the inserts are keyed
-- on slug so a second run reproduces the same catalog with new variant ids.
--
-- ids are generated by gen_random_uuid(). Nothing in the app depends on a
-- fixed product id — artwork and routing key off slug.

begin;

-- order_items references products and product_variants, so it must be emptied
-- before the catalog is replaced.
truncate table public.order_items, public.order_events, public.orders, public.email_log restart identity;

delete from public.product_variants;
delete from public.products;

insert into public.products (id, name, slug, description, status, category, sort_order)
values (
  gen_random_uuid(),
  'Everyday Cotton Tee',
  'everyday-cotton-tee',
  'A 180gsm combed cotton tee with a relaxed fit that holds its shape wash after wash.',
  'active',
  'Apparel',
  0
);

insert into public.product_variants (id, product_id, title, sku, price_cents, currency, stock, position, is_default, is_active)
select
  gen_random_uuid(), p.id,
  'Bone / S',
  'LS-EVE-01-01',
  2800,
  'usd',
  12,
  0,
  true,
  true
from public.products p where p.slug = 'everyday-cotton-tee';

insert into public.product_variants (id, product_id, title, sku, price_cents, currency, stock, position, is_default, is_active)
select
  gen_random_uuid(), p.id,
  'Bone / M',
  'LS-EVE-01-02',
  2800,
  'usd',
  18,
  1,
  false,
  true
from public.products p where p.slug = 'everyday-cotton-tee';

insert into public.product_variants (id, product_id, title, sku, price_cents, currency, stock, position, is_default, is_active)
select
  gen_random_uuid(), p.id,
  'Bone / L',
  'LS-EVE-01-03',
  2800,
  'usd',
  4,
  2,
  false,
  true
from public.products p where p.slug = 'everyday-cotton-tee';

insert into public.product_variants (id, product_id, title, sku, price_cents, currency, stock, position, is_default, is_active)
select
  gen_random_uuid(), p.id,
  'Ink / M',
  'LS-EVE-01-04',
  2800,
  'usd',
  9,
  3,
  false,
  true
from public.products p where p.slug = 'everyday-cotton-tee';

insert into public.products (id, name, slug, description, status, category, sort_order)
values (
  gen_random_uuid(),
  'Heavyweight Hoodie',
  'heavyweight-hoodie',
  'Brushed loopback fleece with a double-layered hood and ribbed cuffs that keep their form.',
  'active',
  'Apparel',
  1
);

insert into public.product_variants (id, product_id, title, sku, price_cents, currency, stock, position, is_default, is_active)
select
  gen_random_uuid(), p.id,
  'Slate / S',
  'LS-HEA-02-01',
  7400,
  'usd',
  7,
  0,
  true,
  true
from public.products p where p.slug = 'heavyweight-hoodie';

insert into public.product_variants (id, product_id, title, sku, price_cents, currency, stock, position, is_default, is_active)
select
  gen_random_uuid(), p.id,
  'Slate / M',
  'LS-HEA-02-02',
  7400,
  'usd',
  11,
  1,
  false,
  true
from public.products p where p.slug = 'heavyweight-hoodie';

insert into public.product_variants (id, product_id, title, sku, price_cents, currency, stock, position, is_default, is_active)
select
  gen_random_uuid(), p.id,
  'Slate / L',
  'LS-HEA-02-03',
  7400,
  'usd',
  0,
  2,
  false,
  true
from public.products p where p.slug = 'heavyweight-hoodie';

insert into public.product_variants (id, product_id, title, sku, price_cents, currency, stock, position, is_default, is_active)
select
  gen_random_uuid(), p.id,
  'Oat / M',
  'LS-HEA-02-04',
  7400,
  'usd',
  6,
  3,
  false,
  true
from public.products p where p.slug = 'heavyweight-hoodie';

insert into public.products (id, name, slug, description, status, category, sort_order)
values (
  gen_random_uuid(),
  'Canvas Tote Bag',
  'canvas-tote-bag',
  'Sixteen-ounce natural canvas, reinforced handles, and an interior pocket sized for a laptop.',
  'active',
  'Accessories',
  2
);

insert into public.product_variants (id, product_id, title, sku, price_cents, currency, stock, position, is_default, is_active)
select
  gen_random_uuid(), p.id,
  'Natural',
  'LS-CAN-03-01',
  3200,
  'usd',
  25,
  0,
  true,
  true
from public.products p where p.slug = 'canvas-tote-bag';

insert into public.product_variants (id, product_id, title, sku, price_cents, currency, stock, position, is_default, is_active)
select
  gen_random_uuid(), p.id,
  'Black',
  'LS-CAN-03-02',
  3200,
  'usd',
  14,
  1,
  false,
  true
from public.products p where p.slug = 'canvas-tote-bag';

insert into public.products (id, name, slug, description, status, category, sort_order)
values (
  gen_random_uuid(),
  'Ceramic Pour-Over Mug',
  'ceramic-pour-over-mug',
  'Stoneware mug with a matte exterior and a glazed interior that resists staining.',
  'active',
  'Home',
  3
);

insert into public.product_variants (id, product_id, title, sku, price_cents, currency, stock, position, is_default, is_active)
select
  gen_random_uuid(), p.id,
  'Chalk / 320ml',
  'LS-CER-04-01',
  2400,
  'usd',
  30,
  0,
  true,
  true
from public.products p where p.slug = 'ceramic-pour-over-mug';

insert into public.product_variants (id, product_id, title, sku, price_cents, currency, stock, position, is_default, is_active)
select
  gen_random_uuid(), p.id,
  'Clay / 320ml',
  'LS-CER-04-02',
  2400,
  'usd',
  16,
  1,
  false,
  true
from public.products p where p.slug = 'ceramic-pour-over-mug';

insert into public.product_variants (id, product_id, title, sku, price_cents, currency, stock, position, is_default, is_active)
select
  gen_random_uuid(), p.id,
  'Chalk / 450ml',
  'LS-CER-04-03',
  2700,
  'usd',
  8,
  2,
  false,
  true
from public.products p where p.slug = 'ceramic-pour-over-mug';

insert into public.products (id, name, slug, description, status, category, sort_order)
values (
  gen_random_uuid(),
  'Linen Throw Blanket',
  'linen-throw-blanket',
  'Washed European linen, breathable and softens with every use. Sized for a full bed.',
  'active',
  'Home',
  4
);

insert into public.product_variants (id, product_id, title, sku, price_cents, currency, stock, position, is_default, is_active)
select
  gen_random_uuid(), p.id,
  'Fog',
  'LS-LIN-05-01',
  8900,
  'usd',
  5,
  0,
  true,
  true
from public.products p where p.slug = 'linen-throw-blanket';

insert into public.product_variants (id, product_id, title, sku, price_cents, currency, stock, position, is_default, is_active)
select
  gen_random_uuid(), p.id,
  'Terracotta',
  'LS-LIN-05-02',
  8900,
  'usd',
  3,
  1,
  false,
  true
from public.products p where p.slug = 'linen-throw-blanket';

insert into public.products (id, name, slug, description, status, category, sort_order)
values (
  gen_random_uuid(),
  'Leather Card Wallet',
  'leather-card-wallet',
  'Full-grain vegetable-tanned leather, four slots, and a centre pocket for folded notes.',
  'active',
  'Accessories',
  5
);

insert into public.product_variants (id, product_id, title, sku, price_cents, currency, stock, position, is_default, is_active)
select
  gen_random_uuid(), p.id,
  'Tan',
  'LS-LEA-06-01',
  5600,
  'usd',
  20,
  0,
  true,
  true
from public.products p where p.slug = 'leather-card-wallet';

insert into public.product_variants (id, product_id, title, sku, price_cents, currency, stock, position, is_default, is_active)
select
  gen_random_uuid(), p.id,
  'Espresso',
  'LS-LEA-06-02',
  5600,
  'usd',
  13,
  1,
  false,
  true
from public.products p where p.slug = 'leather-card-wallet';

insert into public.products (id, name, slug, description, status, category, sort_order)
values (
  gen_random_uuid(),
  'Minimal Desk Lamp',
  'minimal-desk-lamp',
  'Matte powder-coated base with a stepless dimmer and a warm, low-glare LED panel.',
  'active',
  'Home',
  6
);

insert into public.product_variants (id, product_id, title, sku, price_cents, currency, stock, position, is_default, is_active)
select
  gen_random_uuid(), p.id,
  'Black',
  'LS-MIN-07-01',
  11400,
  'usd',
  9,
  0,
  true,
  true
from public.products p where p.slug = 'minimal-desk-lamp';

insert into public.product_variants (id, product_id, title, sku, price_cents, currency, stock, position, is_default, is_active)
select
  gen_random_uuid(), p.id,
  'White',
  'LS-MIN-07-02',
  11400,
  'usd',
  2,
  1,
  false,
  true
from public.products p where p.slug = 'minimal-desk-lamp';

insert into public.products (id, name, slug, description, status, category, sort_order)
values (
  gen_random_uuid(),
  'Merino Wool Socks',
  'merino-wool-socks',
  'Temperature-regulating merino blend with a reinforced heel and a flat, seam-free toe.',
  'active',
  'Apparel',
  7
);

insert into public.product_variants (id, product_id, title, sku, price_cents, currency, stock, position, is_default, is_active)
select
  gen_random_uuid(), p.id,
  'Charcoal / M',
  'LS-MER-08-01',
  1800,
  'usd',
  40,
  0,
  true,
  true
from public.products p where p.slug = 'merino-wool-socks';

insert into public.product_variants (id, product_id, title, sku, price_cents, currency, stock, position, is_default, is_active)
select
  gen_random_uuid(), p.id,
  'Charcoal / L',
  'LS-MER-08-02',
  1800,
  'usd',
  22,
  1,
  false,
  true
from public.products p where p.slug = 'merino-wool-socks';

insert into public.product_variants (id, product_id, title, sku, price_cents, currency, stock, position, is_default, is_active)
select
  gen_random_uuid(), p.id,
  'Rust / M',
  'LS-MER-08-03',
  1800,
  'usd',
  0,
  2,
  false,
  true
from public.products p where p.slug = 'merino-wool-socks';

commit;

-- Make PostgREST pick up the new rows without a restart.
notify pgrst, 'reload schema';
